# Generated by Django 3.1 on 2020-08-29 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexe', models.CharField(choices=[('Masculin', 'Masculin'), ('Féminin', 'Féminin')], max_length=9, verbose_name='sexe')),
                ('nom', models.CharField(max_length=25, verbose_name='nom')),
                ('prenom', models.CharField(max_length=25, verbose_name='prénom')),
                ('date_nais', models.DateField(verbose_name='date de naissance')),
                ('lieu_nais', models.CharField(max_length=25, verbose_name='lieu de naissance')),
            ],
        ),
    ]
